<?zpl version="2.0"?>
<smil>
  <head>
    <meta name="totalDuration" content="8561569" />
    <meta name="itemCount" content="38" />
    <meta name="generator" content="Entertainment Platform -- 10.20122.1112.0" />
    <title>Best OMG Songs</title>
  </head>
  <body>
    <seq>
      <media src="C:\Users\navkc\Music\Limp Bizkit - (Mission Impossible 2).mp3" albumTitle="Limp Bizkit - (Mission Impossible 2)" albumArtist="Unknown Artist" trackTitle="Limp Bizkit - (Mission Impossible 2)" trackArtist="Unknown Artist" duration="314180" />
      <media src="C:\Users\navkc\Music\Mission Impossible II Theme Instrumental.mp3" albumTitle="Mission Impossible II Theme Instrumental" albumArtist="Unknown Artist" trackTitle="Mission Impossible II Theme Instrumental" trackArtist="Unknown Artist" duration="330640" />
      <media src="C:\Users\navkc\Music\007 James Bond Theme.mp3" albumTitle="007 : James Bond : Theme" albumArtist="Unknown Artist" trackTitle="007 : James Bond : Theme" trackArtist="Unknown Artist" duration="173620" />
      <media src="C:\Users\navkc\Music\All James Bond Movie Theme Songs.mp3" albumTitle="All James Bond Movie Theme Songs" albumArtist="Unknown Artist" trackTitle="All James Bond Movie Theme Songs" trackArtist="Unknown Artist" duration="618460" />
      <media src="C:\Users\navkc\Music\Preston Sings Faded by Alan Walker.mp3" albumTitle="Preston Sings Faded by Alan Walker" albumArtist="Unknown Artist" trackTitle="Preston Sings Faded by Alan Walker" trackArtist="Unknown Artist" duration="100420" />
      <media src="C:\Users\navkc\Music\Preston Sings Creeper Aww Man (Revenge).mp3" albumTitle="Preston Sings Creeper Aww Man (Revenge)" albumArtist="Unknown Artist" trackTitle="Preston Sings Creeper Aww Man (Revenge)" trackArtist="Unknown Artist" duration="75620" />
      <media src="C:\Users\navkc\Music\Preston Sings Marshmello - Happier.mp3" albumTitle="Preston Sings Marshmello - Happier" albumArtist="Unknown Artist" trackTitle="Preston Sings Marshmello - Happier" trackArtist="Unknown Artist" duration="70180" />
      <media src="C:\Users\navkc\Music\Jelly, Slogo &amp; Crainer Sing Savage Love - Copy.mp3" albumTitle="Jelly, Slogo &amp; Crainer Sing Savage Love" albumArtist="Unknown Artist" trackTitle="Jelly, Slogo &amp; Crainer Sing Savage Love" trackArtist="Unknown Artist" duration="84220" />
      <media src="C:\Users\navkc\Music\YouTubers Sing Believer (1.5 MILLION SUBSCRIBERS).mp3" albumTitle="YouTubers Sing Believer (1.5 MILLION SUBSCRIBERS)" albumArtist="Unknown Artist" trackTitle="YouTubers Sing Believer (1.5 MILLION SUBSCRIBERS)" trackArtist="Unknown Artist" duration="87340" />
      <media src="C:\Users\navkc\Music\YouTubers Sing Dance Monkey (1 MILLION SUBSCRIBERS).mp3" albumTitle="YouTubers Sing Dance Monkey (1 MILLION SUBSCRIBERS)" albumArtist="Unknown Artist" trackTitle="YouTubers Sing Dance Monkey (1 MILLION SUBSCRIBERS)" trackArtist="Unknown Artist" duration="147360" />
      <media src="C:\Users\navkc\Music\The Mandalorian.mp3" albumTitle="The Mandalorian" albumArtist="Unknown Artist" trackTitle="The Mandalorian" trackArtist="Unknown Artist" duration="198880" />
      <media src="C:\Users\navkc\Music\The Mandalorian OST - Main Theme.mp3" albumTitle="The Mandalorian OST - Main Theme" albumArtist="Unknown Artist" trackTitle="The Mandalorian OST - Main Theme" trackArtist="Unknown Artist" duration="236820" />
      <media src="C:\Users\navkc\Music\Some Things Never Change (From Frozen 2 Sing-Along).mp3" albumTitle="Some Things Never Change (From &quot;Frozen 2&quot;/Sing-Along)" albumArtist="Unknown Artist" trackTitle="Some Things Never Change (From &quot;Frozen 2&quot;/Sing-Along)" trackArtist="Unknown Artist" duration="234260" />
      <media src="C:\Users\navkc\Music\Josh Gad - When I Am Older (From Frozen 2 ).mp3" albumTitle="Josh Gad - When I Am Older (From &quot;Frozen 2&quot;/)" albumArtist="Unknown Artist" trackTitle="Josh Gad - When I Am Older (From &quot;Frozen 2&quot;/)" trackArtist="Unknown Artist" duration="115260" />
      <media src="C:\Users\navkc\Music\FROZEN In Summer Song - Olaf Official Disney UK.mp3" albumTitle="FROZEN | &quot;In Summer&quot; Song - Olaf | Official Disney UK" albumArtist="Unknown Artist" trackTitle="FROZEN | &quot;In Summer&quot; Song - Olaf | Official Disney UK" trackArtist="Unknown Artist" duration="119800" />
      <media albumTitle="Josh Gad - When I Am Older (From &quot;Frozen 2: First Listen&quot;)" albumArtist="Unknown Artist" trackTitle="Josh Gad - When I Am Older (From &quot;Frozen 2: First Listen&quot;)" trackArtist="Unknown Artist" duration="35520" />
      <media src="C:\Users\navkc\Music\All Siren Calls From Disney s Frozen II .mp3" albumTitle="All Siren Calls From Disney's &quot;Frozen II&quot;" albumArtist="Unknown Artist" trackTitle="All Siren Calls From Disney's &quot;Frozen II&quot;" trackArtist="Unknown Artist" duration="99080" />
      <media src="C:\Users\navkc\Music\Idina Menzel, AURORA - Into the Unknown (From Frozen 2 ).mp3" albumTitle="Idina Menzel, AURORA - Into the Unknown (From &quot;Frozen 2&quot;/)" albumArtist="Unknown Artist" trackTitle="Idina Menzel, AURORA - Into the Unknown (From &quot;Frozen 2&quot;/)" trackArtist="Unknown Artist" duration="199900" />
      <media src="C:\Users\navkc\Music\Idina Menzel - Let It Go (from Frozen) (Official Video).mp3" albumTitle="Idina Menzel - Let It Go (from Frozen) (Official Video)" albumArtist="Unknown Artist" trackTitle="Idina Menzel - Let It Go (from Frozen) (Official Video)" trackArtist="Unknown Artist" duration="225220" />
      <media src="C:\Users\navkc\Music\Master - Master the Blaster Thalapathy Vijay AnirudhRavichander LokeshKanagaraj.mp3" albumTitle="Master - Master the Blaster | Thalapathy Vijay | AnirudhRavichander | LokeshKanagaraj" albumArtist="Unknown Artist" trackTitle="Master - Master the Blaster | Thalapathy Vijay | AnirudhRavichander | LokeshKanagaraj" trackArtist="Unknown Artist" duration="92500" />
      <media src="C:\Users\navkc\Music\Master - Vaathi Coming Thalapathy Vijay Anirudh Ravichander Lokesh Kanagaraj.mp3" albumTitle="Master - Vaathi Coming | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" albumArtist="Unknown Artist" trackTitle="Master - Vaathi Coming | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" trackArtist="Unknown Artist" duration="234180" />
      <media src="C:\Users\navkc\Music\Master - Kutti Story Video Thalapathy Vijay Anirudh Ravichander Lokesh Kanagaraj.mp3" albumTitle="Master - Kutti Story Video | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" albumArtist="Unknown Artist" trackTitle="Master - Kutti Story Video | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" trackArtist="Unknown Artist" duration="299100" />
      <media src="C:\Users\navkc\Music\Master - Vaathi Raid Thalapathy Vijay Anirudh Ravichander Lokesh Kanagaraj.mp3" albumTitle="Master - Vaathi Raid | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" albumArtist="Unknown Artist" trackTitle="Master - Vaathi Raid | Thalapathy Vijay | Anirudh Ravichander | Lokesh Kanagaraj" trackArtist="Unknown Artist" duration="216100" />
      <media src="C:\Users\navkc\Music\The lion King bgm 🦁.mp3" albumTitle="The lion King bgm 🦁" albumArtist="Unknown Artist" trackTitle="The lion King bgm 🦁" trackArtist="Unknown Artist" duration="81060" />
      <media src="C:\Users\navkc\Music\TERMINATOR 2 - THEME piano cover Synthesia.mp3" albumTitle="TERMINATOR 2 - THEME | piano cover| Synthesia" albumArtist="Unknown Artist" trackTitle="TERMINATOR 2 - THEME | piano cover| Synthesia" trackArtist="Unknown Artist" duration="117120" />
      <media src="C:\Users\navkc\Music\Assassin s Creed Valhalla Epic Theme - Berserkir (Ezio s Family).mp3" albumTitle="Assassin's Creed Valhalla Epic Theme - Berserkir (Ezio's Family)" albumArtist="Unknown Artist" trackTitle="Assassin's Creed Valhalla Epic Theme - Berserkir (Ezio's Family)" trackArtist="Unknown Artist" duration="143740" />
      <media src="C:\Users\navkc\Music\Assassin s Creed 2 OST Jesper Kyd - Ezio s Family (Track 03).mp3" albumTitle="Assassin's Creed 2 OST / Jesper Kyd - Ezio's Family (Track 03)" albumArtist="Unknown Artist" trackTitle="Assassin's Creed 2 OST / Jesper Kyd - Ezio's Family (Track 03)" trackArtist="Unknown Artist" duration="239620" />
      <media src="C:\Users\navkc\Music\VATHAPI GANAPATHIM- GHANTASALA.mp3" albumTitle="VATHAPI GANAPATHIM- GHANTASALA" albumArtist="Unknown Artist" trackTitle="VATHAPI GANAPATHIM- GHANTASALA" trackArtist="Unknown Artist" duration="189920" />
      <media src="C:\Users\navkc\Music\Raag BHUPALI On FLUTE by Pt. Hariprasad Chaurasia.mp3" albumTitle="Raag BHUPALI On FLUTE by Pt. Hariprasad Chaurasia" albumArtist="Unknown Artist" trackTitle="Raag BHUPALI On FLUTE by Pt. Hariprasad Chaurasia" trackArtist="Unknown Artist" duration="1844340" />
      <media src="C:\Users\navkc\Music\Aathma-Raama-Brodha-V(RaagMedia.Com).mp3" albumTitle="(RaagMedia.Com)" albumArtist="Brodha V (RaagMedia.Com)" trackTitle="Aathma Raama (RaagMedia.Com)" trackArtist="Brodha V (RaagMedia.Com)" duration="234960" />
      <media src="C:\Users\navkc\Music\Ala vaikunthapurramuloo Heroine BGM Allu arjun Pooja Hegde Trivikram Thaman.mp3" albumTitle="Ala vaikunthapurramuloo Heroine BGM Allu arjun Pooja Hegde Trivikram Thaman" albumArtist="Unknown Artist" trackTitle="Ala vaikunthapurramuloo Heroine BGM Allu arjun Pooja Hegde Trivikram Thaman" trackArtist="Unknown Artist" duration="52700" />
      <media src="C:\Users\navkc\Music\#AlaVaikunthapurramuloo - Sittharala Sirapadu Allu Arjun Trivikram Thaman S #AA19.mp3" albumTitle="#AlaVaikunthapurramuloo - Sittharala Sirapadu Allu Arjun Trivikram | Thaman S |#AA19" albumArtist="Unknown Artist" trackTitle="#AlaVaikunthapurramuloo - Sittharala Sirapadu Allu Arjun Trivikram | Thaman S |#AA19" trackArtist="Unknown Artist" duration="183940" />
      <media src="C:\Users\navkc\Music\#AlaVaikunthapurramuloo - OMG Daddy Full Video Song (4K) Allu Arjun Trivikram Thaman S #AA19.mp3" albumTitle="#AlaVaikunthapurramuloo - OMG Daddy Full Video Song (4K) | Allu Arjun | Trivikram | Thaman S |#AA19" albumArtist="Unknown Artist" trackTitle="#AlaVaikunthapurramuloo - OMG Daddy Full Video Song (4K) | Allu Arjun | Trivikram | Thaman S |#AA19" trackArtist="Unknown Artist" duration="231480" />
      <media src="C:\Users\navkc\Music\#AlaVaikunthapurramuloo - Ramuloo Ramulaa Full Video Song Allu Arjun Trivikram Thaman S.mp3" albumTitle="#AlaVaikunthapurramuloo - Ramuloo Ramulaa Full Video Song Allu Arjun Trivikram | Thaman S" albumArtist="Unknown Artist" trackTitle="#AlaVaikunthapurramuloo - Ramuloo Ramulaa Full Video Song Allu Arjun Trivikram | Thaman S" trackArtist="Unknown Artist" duration="273320" />
      <media src="C:\Users\navkc\Music\FDM_Ed_Sheeran_-_Shape_of_You_320_kbps_Release_Date_-_06.01.2017_(mp3.pm).mp3" albumTitle="Shape of You - Single" albumArtist="Ed Sheeran" trackTitle="Shape of You" trackArtist="Ed Sheeran" duration="233769" />
      <media src="C:\Users\navkc\Music\Imagine Dragons - Believer.mp3" albumTitle="Imagine Dragons - Believer" albumArtist="Unknown Artist" trackTitle="Imagine Dragons - Believer" trackArtist="Unknown Artist" duration="204400" />
      <media src="C:\Users\navkc\Music\Fortnite Dance Moves (Default Dance) Emote - Future Bass Remix.mp3" albumTitle="Fortnite Dance Moves (Default Dance) Emote - Future Bass Remix" albumArtist="Unknown Artist" trackTitle="Fortnite Dance Moves (Default Dance) Emote - Future Bass Remix" trackArtist="Unknown Artist" duration="102460" />
      <media src="C:\Users\navkc\Music\Fortnite Default Dance Remix (Xygon).mp3" albumTitle="Fortnite Default Dance Remix (Xygon)" albumArtist="Unknown Artist" trackTitle="Fortnite Default Dance Remix (Xygon)" trackArtist="Unknown Artist" duration="120080" />
    </seq>
  </body>
</smil>